world:
  global_frame: /world
  maps_package: multimap_server
  maps:
    localization: prmaps/sastena/sastena_cad.yaml
area01:
  global_frame: area01_map
  maps_package: multimap_server
  maps:
    localization: prmaps/sastena/area01.yaml
